# Generated by Django 5.0 on 2023-12-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("P", "Proteina"),
                            ("C", "Carbohidrato"),
                            ("V", "Vegetal"),
                            ("D", "Lacteo"),
                            ("F", "Fruta"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
