# Generated by Django 5.0 on 2023-12-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="group",
            field=models.IntegerField(
                choices=[
                    (0, "Proteina"),
                    (1, "Carbohidrato"),
                    (2, "Vegetal"),
                    (3, "Lacteo"),
                    (4, "Fruta"),
                ],
                default=0,
            ),
        ),
    ]
